FROM nginx:1.29.1-alpine3.22
RUN apk add --no-cache openssl \
    && mkdir -p /etc/nginx/ssl \
    && openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/nginx/ssl/key.pem \
        -out /etc/nginx/ssl/cert.pem \
        -subj "/CN=localhost"
EXPOSE 80 443 8060
CMD ["nginx", "-g", "daemon off;"]
