services:
  next-app-bun:
    build: .
    image: ssr-nextjs-bun-app
    restart: unless-stopped
    networks:
      - app-net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ssr-nextjs-bun-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8060:8060"
    depends_on:
      - next-app-bun
    networks:
      - app-net

networks:
  app-net:
    driver: bridge