---
- name: Create directories for Prometheus and Grafana
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'
  loop:
    - /home/ec2-user/prometheus
    - /home/ec2-user/grafana
    - /home/ec2-user/grafana-provisioning/datasources
    - /home/ec2-user/grafana-provisioning/dashboards

- name: Create Grafana datasource provisioning configuration
  ansible.builtin.template:
    src: prometheus-datasource.yml.j2
    dest: /home/ec2-user/grafana-provisioning/datasources/prometheus.yml

- name: Create Grafana dashboard provider configuration
  ansible.builtin.template:
    src: dashboard-provider.yml.j2
    dest: /home/ec2-user/grafana-provisioning/dashboards/provider.yml

- name: Create directory for dashboards
  ansible.builtin.file:
    path: /home/ec2-user/grafana-dashboards
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Copy NGINX dashboard
  ansible.builtin.copy:
    src: nginx-dashboard.json
    dest: /home/ec2-user/grafana-dashboards/nginx-dashboard.json
    mode: '0644'

- name: Copy System dashboard
  ansible.builtin.copy:
    src: system-dashboard.json
    dest: /home/ec2-user/grafana-dashboards/system-dashboard.json
    mode: '0644'

- name: Copy k6 dashboard
  ansible.builtin.copy:
    src: k6-dashboard.json
    dest: /home/ec2-user/grafana-dashboards/k6-dashboard.json
    mode: '0644'

- name: Create Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /home/ec2-user/prometheus/prometheus.yml

- name: Create Monitoring Telegraf configuration
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /home/ec2-user/telegraf.conf

- name: Create Monitoring docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/ec2-user/docker-compose.yml

- name: Run Monitoring Stack
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: /home/ec2-user/