---
- name: Create directories for Prometheus and Grafana
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'
  loop:
    - /home/ec2-user/prometheus
    - /home/ec2-user/grafana

- name: Create Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /home/ec2-user/prometheus/prometheus.yml

- name: Create Monitoring docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/ec2-user/docker-compose.yml

- name: Run Monitoring Stack
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /home/ec2-user/