---
- name: Copy CSR application files
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../csr-react/"
    dest: /home/ec2-user/csr-react
    rsync_opts:
      - "--exclude=node_modules"

- name: Create nginx log directory for CSR
  ansible.builtin.file:
    path: /var/log/csr-react-nginx
    state: directory
    mode: '0755'
  become: true

- name: Include nginx_log_exporter role for CSR
  include_role:
    name: nginx_log_exporter
  vars:
    nginx_log_path: "/var/log/csr-react-nginx/access.log"

- name: Run CSR App Server
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: /home/ec2-user/csr-react