---
- name: Copy CSR application files
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../csr-react/"
    dest: /home/ec2-user/csr-react
    rsync_opts:
      - "--exclude=node_modules"

- name: Create Telegraf configuration for CSR
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /home/ec2-user/csr-react/telegraf.conf

- name: Run CSR App Server
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: /home/ec2-user/csr-react