---
# Amazon Linux OS tuning for high connection throughput (only for load generators)

- name: Ensure sysctl.d directory exists
  ansible.builtin.file:
    path: /etc/sysctl.d
    state: directory
    mode: "0755"

- name: Configure kernel networking and file descriptor limits for load generation
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-k6-tuning.conf
    mode: "0644"
    content: |
      net.core.somaxconn = 65535
      net.ipv4.ip_local_port_range = 1024 65535
      net.ipv4.tcp_tw_reuse = 1
      net.ipv4.tcp_fin_timeout = 15
      net.ipv4.tcp_max_syn_backlog = 262144
      net.core.netdev_max_backlog = 262144
      net.core.rmem_max = 134217728
      net.core.wmem_max = 134217728
      net.ipv4.tcp_rmem = 4096 87380 134217728
      net.ipv4.tcp_wmem = 4096 65536 134217728
      net.ipv4.tcp_syncookies = 0
      net.ipv4.tcp_timestamps = 1
      net.ipv4.tcp_sack = 1

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
  register: sysctl_apply
  changed_when: "sysctl_apply.rc == 0"

- name: Ensure higher nofile soft/hard limits for ec2-user
  ansible.builtin.copy:
    dest: /etc/security/limits.d/99-k6-nofile.conf
    mode: "0644"
    content: |
      ec2-user soft nofile 250000
      ec2-user hard nofile 250000
