version: '3.8'

services:
  next-app:
    build: .
    image: ssr-nextjs-next-app
    container_name: next-app
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge