services:
  sveltekit-app:
    build:
      context: .
    image: ssr-svelte-kit-app
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge