services:
  next-app-deno:
    build: .
    image: ssr-nextjs-deno-app
    restart: unless-stopped
    networks:
      - app-net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ssr-nextjs-deno-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8060:8060"
    depends_on:
      - next-app-deno
    networks:
      - app-net

networks:
  app-net:
    driver: bridge