services:
  nuxt-app:
    build: .
    image: ssr-nuxt-nuxt-app
    container_name: nuxt-app
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
