---
- name: Download and unarchive node_exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-arm64.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/node_exporter-1.7.0.linux-arm64/node_exporter"

- name: Move node_exporter binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/node_exporter-1.7.0.linux-arm64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    remote_src: true
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Create systemd service file for node_exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"
  become: true
  notify: Reload systemd

- name: Start and enable node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
  become: true
