---
- name: Install Docker
  ansible.builtin.dnf:
    name: docker
    state: present

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to the docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true

- name: Install pip and Docker SDK for Python
  ansible.builtin.dnf:
    name:
      - python3-pip
      - python3-docker
      - git
    state: present

- name: Install Docker Compose Python library (required by docker_compose module)
  ansible.builtin.pip:
    name: docker-compose
    state: present
    extra_args: --user
  become: true

- name: Install Docker Compose
  become: true
  block:
    - name: Create directory for docker plugins
      ansible.builtin.file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: "0755"

    - name: Download and install Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: "0755"
        checksum: "sha256:https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-{{ ansible_architecture }}.sha256"
      retries: 3
      delay: 5

- name: Include node_exporter role
  ansible.builtin.include_role:
    name: node_exporter
