services:
  solid-app:
    build: .
    image: ssr-solid-start-solid-app
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
