# docker-compose.prod.yml

services:
  # The SvelteKit Application Service - running directly without nginx
  sveltekit-app:
    build:
      context: .
    image: ssr-svelte-kit-bun-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8060:8060"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/log/ssr-svelte-kit-bun-nginx:/var/log/nginx
    depends_on:
      - sveltekit-app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge