services:
  svelte-app-bun:
    build:
      context: .
      target: runner
    image: ssr-svelte-kit-bun-app
    restart: unless-stopped
    networks:
      - app-net

  nginx:
    build:
      context: .
      target: nginx
    image: ssr-svelte-kit-bun-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8060:8060"
    depends_on:
      - svelte-app-bun
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
