---
# ansible/ops/test_sync_script.yml
#
# This playbook synchronizes the k6 script to all load generators.
# It should be run before starting any performance tests to ensure
# the latest version of the script is available on the remote hosts.

- name: Deploy k6 script to all load generators
  hosts: role_load_generators
  become: true
  gather_facts: false
  vars:
    local_k6_script_path: "../../../k6/script.js"
    local_k6_extract_path: "../../../k6/extract.js"
    remote_temp_script_path: "/tmp/script.js"
    remote_temp_extract_path: "/tmp/extract.js"

  tasks:
    - name: Ensure the k6 script files exist locally
      delegate_to: localhost
      become: false
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - "{{ local_k6_script_path }}"
        - "{{ local_k6_extract_path }}"
      register: k6_script_files
      failed_when: not k6_script_files.stat.exists

    - name: Copy the k6 scripts to the remote host
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: "{{ local_k6_script_path }}"
          dest: "{{ remote_temp_script_path }}"
        - src: "{{ local_k6_extract_path }}"
          dest: "{{ remote_temp_extract_path }}"
