services:
  qwik-app:
    build: .
    image: ssr-qwik-city-app
    restart: unless-stopped
    networks:
      - app-net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ssr-qwik-city-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8060:8060"
    depends_on:
      - qwik-app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
