{
 "title": "Master Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(node_cpu_seconds_total,server)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "p50 : 0.5, p90 : 0.9, p95 : 0.95, p99 : 0.99, p99.9 : 0.999"
   },
   {
    "name": "my_rate_interval",
    "label": "Rate Interval",
    "query": "$__rate_interval, 15s, 30s, 1m, 5m, 10m, 30m, 1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Successful client page requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "# sum by (server) (rate(k6_http_reqs_total{server=~\"$server\", group=\"::Main page\"}[$my_rate_interval]))\r\nsum by (server) (rate(k6_http_reqs_total{server=~\"$server\", error_code=\"\", resource_type=\"html\", status=\"200\"}[$my_rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Ram Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server) (node_memory_MemTotal_bytes{server=~\"$server\"} - node_memory_MemAvailable_bytes{server=~\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All successful client requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "# sum by (server) (rate(k6_http_reqs_total{server=~\"$server\", group=\"::Main page\"}[$my_rate_interval]))\r\nsum by (server) (rate(k6_http_reqs_total{server=~\"$server\", error_code=\"\", status=\"200\"}[$my_rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (server) (1 - rate(node_cpu_seconds_total{mode=\"idle\", server=~\"$server\"}[$my_rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client latency $percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by (le, server) (rate(k6_http_req_duration_seconds{server=~\"$server\"}[$my_rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System trasmitted bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(node_network_transmit_bytes_total{server=~\"$server\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "# sum by (server) (rate(k6_http_reqs_total{server=~\"$server\", group=\"::Main page\"}[$my_rate_interval]))\r\nsum by (server) (rate(k6_http_reqs_total{server=~\"$server\"}[$my_rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability (Client Perspective)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# sum by (server) (k6_checks_rate)\r\n\r\n# (\r\n#   sum by (server) (rate(k6_http_req_failed{server=~\"$server\"}[$__rate_interval]))\r\n# /\r\n#   sum by (server) (rate(k6_http_reqs{server=~\"$server\"}[$__rate_interval]))\r\n# ) * 100 or vector(0)\r\n\r\n# avg by (server) (k6_http_req_failed_rate{error!=\"\", server=~\"$server\"} or vector(0))\r\n\r\n# avg by (server) (1-k6_checks_rate{server=~\"$server\"})\r\n\r\n# sum(rate(k6_http_req_failed_total[5m])) / sum(rate(k6_http_reqs_total[5m]))\r\n\r\n# sum by (server) (k6_http_reqs_total{error!=\"\"})\r\n\r\n# Client error rate\r\n# (\r\n#   (\r\n#     sum by (server) (rate(k6_http_reqs_total{error!=\"\", server=~\"$server\"}[$my_rate_interval]))\r\n#   )\r\n#   or on(server)\r\n#   (\r\n#     sum by (server) (rate(k6_http_reqs_total{server=~\"$server\"}[$my_rate_interval])) * 0\r\n#   )\r\n# )\r\n# /\r\n# (\r\n#   sum by (server) (rate(k6_http_reqs_total{server=~\"$server\"}[$my_rate_interval]))\r\n# )\r\n\r\n1-\r\n(\r\n  (\r\n    sum by (server) (rate(k6_http_reqs_total{error_code!=\"\", server=~\"$server\"}[$my_rate_interval]))\r\n  )\r\n  or on(server)\r\n  (\r\n    sum by (server) (rate(k6_http_reqs_total{server=~\"$server\"}[$my_rate_interval])) * 0\r\n  )\r\n)\r\n/\r\n(\r\n  sum by (server) (rate(k6_http_reqs_total{server=~\"$server\"}[$my_rate_interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (server) (1 - (node_memory_MemAvailable_bytes{server=~\"$server\"} / node_memory_MemTotal_bytes{server=~\"$server\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System received bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(node_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx 90p response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (server) (histogram_quantile(0.90, rate(nginx_http_response_time_seconds_hist_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability (Nginx perspective)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# (\r\n#   sum by (server) (rate(nginx_http_response_count_total{status=~\"5xx\"}[$__rate_interval]))\r\n#   or\r\n#   # This part creates a zero-value series for every server that has *any* traffic\r\n#   (sum by (server) (rate(nginx_http_response_count_total[$__rate_interval])) * 0)\r\n# )\r\n# /\r\n# sum by (server) (rate(nginx_http_response_count_total[$__rate_interval]))\r\n\r\n# Nginx error rate\r\n# (\r\n#   (\r\n#     sum by (server) (rate(nginx_http_response_count_total{status=~\"^[45]..\", server=~\"$server\"}[$my_rate_interval]))\r\n#   )\r\n#   or on(server)\r\n#   (\r\n#     sum by (server) (rate(nginx_http_response_count_total{server=~\"$server\"}[$my_rate_interval])) * 0\r\n#   )\r\n# )\r\n# /\r\n# (\r\n#   sum by (server) (rate(nginx_http_response_count_total{server=~\"$server\"}[$my_rate_interval]))\r\n# )\r\n\r\n1-\r\n(\r\n  (\r\n    sum by (server) (rate(nginx_http_response_count_total{status=~\"^[45]..\", server=~\"$server\"}[$my_rate_interval]))\r\n  )\r\n  or on(server)\r\n  (\r\n    sum by (server) (rate(nginx_http_response_count_total{server=~\"$server\"}[$my_rate_interval])) * 0\r\n  )\r\n)\r\n/\r\n(\r\n  sum by (server) (rate(nginx_http_response_count_total{server=~\"$server\"}[$my_rate_interval]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_project) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_project!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx success requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "# sum by (server) (rate(nginx_http_response_count_total[$__rate_interval]))\r\n\r\nsum by (server) (rate(nginx_http_response_count_total{status=~\"^[23]..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (server) (node_netstat_Tcp_CurrEstab{server=~\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx failed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "# sum by (server) (rate(nginx_http_response_count_total[$__rate_interval]))\r\n\r\n# sum by (server) (rate(nginx_http_response_count_total{status=~\"^[45]..\"}[$__rate_interval]))\r\n\r\n(\r\n  sum by (server) (rate(nginx_http_response_count_total{status=~\"^[45]..\"}[$__rate_interval]))\r\n)\r\nor on(server)\r\n(\r\n  sum by (server) (rate(nginx_http_response_count_total[$__rate_interval])) * 0\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K6 Dropped Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by (server) (rate(k6_dropped_iterations_total{server=~\"$server\"}[$my_rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx exporter parse errors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum by (server) (rate(nginx_parse_errors_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_project) (container_memory_usage_bytes{container_label_com_docker_compose_project!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}