services:
  nuxtjs-app:
    build: .
    image: ssr-nuxtjs-app
    restart: unless-stopped
    networks:
      - app-net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8060:8060"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/log/ssr-nuxtjs-nginx:/var/log/nginx
    depends_on:
      - nuxtjs-app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
