services:
  nginx:
    build:
      context: ../../${APPLICATION_DIR}
      target: ${BUILD_TARGET:-nginx}
      additional_contexts:
        infra: ../nginx
    image: mgr-${APPLICATION_ID}-nginx
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-80}:80"
      - "443:443"
      - "8060:8060"
    networks:
      - application-net
    environment:
      - NGINX_TEMPLATE=/etc/nginx/conf.d/default.csr.conf.template

networks:
  application-net:
    driver: bridge
