services:
  react-router-app:
    build: .
    image: ssr-react-router-app
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
