---
- name: Run k6 Performance Test
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Build k6 test archive
      ansible.builtin.command:
        cmd: ./k6/build.sh
        chdir: "{{ playbook_dir }}/.."
      run_once: true # noqa run-once[task]
      changed_when: false

- name: Deploy k6 test archive
  hosts: role_load_generators
  gather_facts: false

  tasks:
    - name: Copy k6 test archive to servers
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../k6/build/k6_archive.tar"
        dest: /home/ec2-user/k6_archive.tar
        mode: "0644"

- name: Trigger k6 test on all load generators
  hosts: role_load_generators
  gather_facts: false

  tasks:
    - name: Start k6 test execution
      ansible.builtin.command: "/home/ec2-user/run_k6.sh"
      async: 7200 # 2 hours. Set to a value longer than your test duration.
      poll: 0 # Fire and forget.
      changed_when: false
