---
- name: Configure All Servers (Common baseline)
  hosts: all
  become: true
  roles:
    - common

- name: Configure Load Generators
  hosts: role_load_generators
  become: true
  roles:
    - load_generator_tuning

- name: Configure All App Servers
  hosts: role_app_servers
  become: true
  roles:
    - app_server
    - cadvisor

- name: Configure Monitoring Server
  hosts: role_monitoring_server
  become: true
  roles:
    - monitoring
