---
- name: Configure All Servers
  hosts: all
  become: yes
  roles:
    - common

- name: Configure CSR App Server
  hosts: app_server_csr
  become: yes
  roles:
    - app_server_csr

- name: Configure SSR App Server
  hosts: app_server_ssr
  become: yes
  roles:
    - app_server_ssr

- name: Configure and deploy load generator for CSR
  hosts: role_load_generator_csr
  become: yes
  vars:
    target_url: "http://{{ hostvars[groups['app_server_csr'][0]]['private_ip'] }}"
    target_server_type: "csr"
  roles:
    - role: load_generator

- name: Configure and deploy load generator for SSR
  hosts: role_load_generator_ssr
  become: yes
  vars:
    target_url: "http://{{ hostvars[groups['app_server_ssr'][0]]['private_ip'] }}"
    target_server_type: "ssr"
  roles:
    - role: load_generator

- name: Configure monitoring server
  hosts: role_monitoring_server
  become: yes
  roles:
    - monitoring 