---
# ansible/stop_all_tests.yml
#
# This playbook stops and removes all k6 test containers across all
# load generator hosts.
#
- name: Stop All k6 Performance Tests
  hosts: role_load_generators
  become: true
  gather_facts: false

  tasks:
    - name: Get a list of running k6 test containers
      # noqa: command-instead-of-shell
      # Shell is required here for the --format templating which is a shell feature.
      ansible.builtin.shell: >-
        docker ps --filter "name=k6_" --format "{{ '{{' }}.Names{{ '}}' }}"
      register: k6_containers_result
      changed_when: false

    - name: Stop and remove the identified k6 containers
      when: k6_containers_result.stdout_lines | length > 0
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: true
      loop: "{{ k6_containers_result.stdout_lines }}"
      register: stop_result

    - name: Report on stopped containers
      ansible.builtin.debug:
        msg: "Stopped and removed {{ stop_result.results | length }} k6 test container(s)."
      when: stop_result.results is defined and stop_result.results | length > 0

    - name: Report if no containers were found
      ansible.builtin.debug:
        msg: "No running k6 test containers were found to stop."
      when: k6_containers_result.stdout_lines | length == 0
