---
- name: Stop k6 Performance Test
  hosts: role_load_generators
  gather_facts: false
  become: true

  tasks:
    - name: Discover running k6 containers by ancestor image
      community.docker.docker_host_info:
        containers: true
        containers_filters:
          ancestor: "grafana/k6:1.1.0"
      register: docker_info

    - name: Stop all found k6 containers
      community.docker.docker_container:
        # CORRECTED: Use the universally available 'regex_replace' filter.
        # This finds the '/' at the start of the string ('^/') and removes it.
        name: "{{ item.Names[0] | regex_replace('^/', '') }}"
        state: stopped
      loop: "{{ docker_info.containers | default([]) }}"

    - name: Report on action taken
      ansible.builtin.debug:
        msg: >-
          {% set found_containers = docker_info.containers | default([]) %}
          {% if found_containers | length > 0 %}
          Stopped {{ found_containers | length }} k6 container(s): {{ found_containers | map(attribute='Names') | list | join(', ') }}
          {% else %}
          No running k6 containers were found to stop.
          {% endif %}
