version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "8080:80"
    networks:
      - monitoring

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    command: -nginx.scrape-uri=http://nginx/stub_status
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.8.1
    ports:
      - "9100:9100"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge 