services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_REVISION: ${GIT_REVISION:-dev}
    environment:
      - DENO_DEPLOYMENT_ID=${GIT_REVISION:-dev}
    command: ["deno", "serve", "-A", "_fresh/server.js"]
    networks:
      - app-net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8060:8060"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/log/ssr-fresh-nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
