services:
  analogjs-app:
    build: .
    image: ssr-analogjs-analogjs-app
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
