version: '3.8'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000"
    networks:
      - monitoring

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - next-app
    networks:
      - monitoring

  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:1.1.0
    restart: unless-stopped
    command: -nginx.scrape-uri http://nginx:8080/stub_status
    ports:
      - "9114:9113"
    depends_on:
      - nginx
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.8.1
    ports:
      - "9101:9100"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge 