version: '3.8'

services:
  next-app:
    build: .
    image: ssr-nextjs-next-app
    container_name: next-app
    restart: unless-stopped
    networks:
      - app-net

  nginx:
    image: nginx:1.26.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "8060:8060"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/log/ssr-nextjs-nginx:/var/log/nginx
    depends_on:
      - next-app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge