version: '3.8'

services:
  next-app:
    build: .
    image: ssr-nextjs-next-app
    container_name: next-app
    restart: unless-stopped
    networks:
      - app-net

  nginx:
    image: nginx:1.26.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "8060:8060"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:8124"
        tag: "nginx"
    depends_on:
      - next-app
      - telegraf
    networks:
      - app-net

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    restart: unless-stopped
    ports:
      - "9273:9273" # Prometheus
      - "8124:8124/udp" # Syslog
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - app-net

networks:
  app-net:
    driver: bridge 