LoadModule mpm_event_module modules/mod_mpm_event.so

<IfModule mpm_event_module>
    StartServers              4
    ServerLimit               32
    ThreadLimit               64
    ThreadsPerChild           64
    MaxRequestWorkers         2048
    MinSpareThreads           128
    MaxSpareThreads           512
    AsyncRequestWorkerFactor  2
    MaxConnectionsPerChild    0
</IfModule>
