---
- name: Copy SSR application files
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../ssr-nextjs/"
    dest: /home/ec2-user/ssr-nextjs
    rsync_opts:
      - "--exclude=.next"

- name: Create nginx log directory for SSR
  ansible.builtin.file:
    path: /var/log/ssr-nextjs-nginx
    state: directory
    mode: '0755'
  become: true

- name: Include nginx_log_exporter role for SSR
  include_role:
    name: nginx_log_exporter
  vars:
    nginx_log_path: "/var/log/ssr-nextjs-nginx/access.log"

- name: Run SSR App Server
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: /home/ec2-user/ssr-nextjs