---
- name: Extract project name from app_dir path
  ansible.builtin.set_fact:
    project_name: "{{ app_dir.split('/')[-1] }}"

- name: Copy application files
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../{{ app_dir }}/"
    dest: "/home/ec2-user/{{ project_name }}"
    rsync_opts:
      - "--exclude=node_modules"
      - "--exclude=.next"

- name: Create nginx log directory
  ansible.builtin.file:
    path: "/var/log/{{ project_name }}-nginx"
    state: directory
    mode: "0755"
  become: true

- name: Include nginx_log_exporter role
  ansible.builtin.include_role:
    name: nginx_log_exporter
  vars:
    nginx_log_exporter_log_path: "/var/log/{{ project_name }}-nginx/access.log"

- name: Ensure App Server stack is running
  community.docker.docker_compose_v2:
    project_src: "/home/ec2-user/{{ project_name }}"
    build: always
    recreate: always
